youtube_url: "https://youtu.be/O6I696BE1x4"

mulan_file: "./lyrics.mulan"

languages:
  - es
  - fr
  - en

output_dir: "./out"

alignment:
  merged_fix_max_group_gap: 1.25
  merged_fix_min_group_segments: 3
  merged_fix_duration_factor: 1.5
  max_distance_ratio: 0.05
  search_window: 12
  insert_missing_between_matches: true
  max_merged_chars: 42
  max_missing_lines: 1

ass:
  play_res_x: 1920
  play_res_y: 1080
  font_name: Arial
  font_size: 54
  margin_v: 45
  line_gap: 72
  max_tracks: 3
  max_chars_per_line: 42

translation:
  enabled: true
  model_path: "/home/drodriguez/dev/opus-mt-fr-es"
  source_language: "fr"
  target_language: "es"
  max_length: 256
  local_files_only: true
  device: "cpu"
  num_beams: 1
  log_progress: true
  skip_if_target_detected: true

youtube_download:
  enabled: false
  format: "bv*[height<=720]+ba/b[height<=720]/best"
  cookies_from_browser: ""
  cookies: ""
  remote_components: ""
  no_check_certificate: false

burn:
  enabled: true
  # Si la vidéo YouTube n'est pas récupérable par yt-dlp, renseigner une vidéo locale ici.
  input_video: "/home/drodriguez/Vidéos/rmc.mp4"
  output_video: "./out/video_subtitled.mp4"
